[tool.poetry]
name = "langton"
version = "0.1.0"
description = ""
authors = ["Sabrina Johnson"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
pygame = "^2.5.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
